okLims/Controllers/UserRoleController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using okLims.Data;
using okLims.Models;
using okLims.Models.AccountViewModels;
using okLims.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace okLims.Controllers
{
    namespace okLims.Controllers
    {
        public class UserRoleController : Controller
        {
            private readonly UserManager<ApplicationUser> _userManager;

            public UserRoleController(UserManager<ApplicationUser> userManager)
            {
                _userManager = userManager;
            }


            [Authorize(Roles = Pages.MainMenu.User.RoleName)]
            public IActionResult Index()
            {
                return View();
            }

            [Authorize(Roles = Pages.MainMenu.ChangePassword.RoleName)]
            public IActionResult ChangePassword()
            {
                return View();
            }

            [Authorize(Roles = Pages.MainMenu.Role.RoleName)]
            public IActionResult Role()
            {
                return View();
            }

            [Authorize(Roles = Pages.MainMenu.ChangeRole.RoleName)]
            public IActionResult ChangeRole()
            {
                return View();
            }

            [Authorize]
            public async Task<IActionResult> ApplicationUser()
            {
                ApplicationUser user = await _userManager.GetUserAsync(User);
                return View(user);
            }
        }
    }
}

okLims/Views/Shared/_Adminlte.cshtml
<!DOCTYPE html>
@inject UserManager<ApplicationUser> UserManager
@inject SignInManager<ApplicationUser> SignInManager
@inject okLims.Data.ApplicationDbContext Context
@{

    ApplicationUser appUser = await UserManager.GetUserAsync(User);

}
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>@ViewData["Title"] - BioreactorLims</title>
    <link href="http://cdn.syncfusion.com/ej2/ej2-base/styles/material.css" rel="stylesheet" type="text/css" />
    <link href="http://cdn.syncfusion.com/ej2/ej2-popups/styles/material.css" rel="stylesheet" type="text/css" />
    <!-- Essential JS 2 material theme -->
    <link href="http://cdn.syncfusion.com/ej2/ej2-grids/styles/material.css" rel="stylesheet" type="text/css" />
    <!-- Bootstrap 3.3.7 -->
    <link rel="stylesheet" href="~/adminlte/components/bootstrap/dist/css/bootstrap.min.css">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/adminlte/components/font-awesome/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="~/adminlte/components/Ionicons/css/ionicons.min.css">
    <!-- Pace style -->
    <link rel="stylesheet" href="~/adminlte/plugins/pace/pace.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/adminlte/dist/css/AdminLTE.min.css">
    <!-- AdminLTE Skins. Choose a skin from the css/skins
         folder instead of downloading all of them to reduce the load. -->
    <link rel="stylesheet" href="~/adminlte/dist/css/skins/_all-skins.min.css">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <!-- Google Font -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">

    <!--Snycfusion-->
    <link href="~/content/ejthemes/bootstrap-theme/ej.web.all.min.css" rel="stylesheet" />
    <link href="~/content/default-responsive.css" rel="stylesheet" />
    <link href="~/content/ejthemes/responsive-css/ej.responsive.css" rel="stylesheet" />
    <link href="~/content/ejthemes/responsive-css/ejgrid.responsive.css" rel="stylesheet" />
    <script src="http://cdn.syncfusion.com/ej2/ej2-base/dist/global/ej2-base.min.js" type="text/javascript"></script>
    <script src="http://cdn.syncfusion.com/ej2/ej2-data/dist/global/ej2-data.min.js" type="text/javascript"></script>
    <script src="http://cdn.syncfusion.com/ej2/ej2-popups/dist/global/ej2-popups.min.js" type="text/javascript"></script>
    <!-- Essential JS 2 Grid's global script -->
    <script src="http://cdn.syncfusion.com/ej2/ej2-grids/dist/global/ej2-grids.min.js" type="text/javascript"></script>

    @RenderSection("Styles", required: false)

</head>
<body class="hold-transition skin-blue fixed sidebar-mini">
    <div class="wrapper">
        @Html.Partial("_AdminlteMainHeader", appUser)
        <!-- Left side column. contains the logo and sidebar -->
        @Html.Partial("_AdminlteMainSidebar", appUser)
        <!-- Content Wrapper. Contains page content -->
        @RenderBody()
        <!-- /.content-wrapper -->
        @Html.Partial("_AdminlteFooter")
    </div>
    <!-- ./wrapper -->
    <!--AdminLTE-->
    <!-- jQuery 3 -->
    <script src="~/adminlte/components/jquery/dist/jquery.min.js"></script>
    <!-- Bootstrap 3.3.7 -->
    <script src="~/adminlte/components/bootstrap/dist/js/bootstrap.min.js"></script>
    <!-- Slimscroll -->
    <script src="~/adminlte/components/jquery-slimscroll/jquery.slimscroll.min.js"></script>
    <!-- FastClick -->
    <script src="~/adminlte/components/fastclick/lib/fastclick.js"></script>
    <!-- AdminLTE App -->
    <script src="~/adminlte/dist/js/adminlte.min.js"></script>
    <!-- PACE -->
    <script src="~/adminlte/components/PACE/pace.min.js"></script>

    <!--Syncfusion-->
    <script src="~/scripts/jsrender.min.js"></script>
    <script src="https://cdn.syncfusion.com/ej2/dist/ej2.min.js"></script>
    <script src="~/scripts/ej.web.all.min.js" type="text/javascript"></script> 
    <script src="~/scripts/properties.js" type="text/javascript"></script>
    <script src="~/scripts/jquery.validate.min.js"></script>
    <script src="~/scripts/jquery.validate.unobtrusive.min.js"></script>

    @RenderSection("Scripts", required: false)

</body>
</html>

<

okLims/Views/Shared/_AdminlteBlank.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>@ViewData["Title"]</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.7 -->
    <link rel="stylesheet" href="~/adminlte/components/bootstrap/dist/css/bootstrap.min.css">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/adminlte/components/font-awesome/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="~/adminlte/components/Ionicons/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/adminlte/dist/css/AdminLTE.min.css">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <a href="~/Views/Shared/_ValidationScriptsPartial.cshtml">~/Views/Shared/_ValidationScriptsPartial.cshtml</a>
    <!-- Google Font -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">

    @RenderSection("Styles", required: false)

</head>
<body class="hold-transition lockscreen" style="background-image: url('/images/fractal.png') ; background-size: cover; ">
    <!-- Automatic element centering -->
    <div class="lockscreen-wrapper">
        @RenderBody()
        <div class="text-center">
            <a href="@Url.Action("Login", "Account")">Or sign in as a different user</a>
        </div>

    </div>
    <!-- /.center -->
    <!-- jQuery 3 --->
    <script src="~/adminlte/components/jquery/dist/jquery.min.js"></script>

    <script src="~/adminlte/plugins/iCheck/icheck.min.js"></script>
    <script src="~/adminlte/components/bootstrap/dist/js/bootstrap.min.js"></script>


    @RenderSection("Scripts", required: false)
</body>
</html>

okLims/Views/Shared/_AdminlteControlSidebar.cshtml
<aside class="control-sidebar control-sidebar-dark">
    <!-- Create the tabs -->
    <ul class="nav nav-tabs nav-justified control-sidebar-tabs">
        <li><a href="#control-sidebar-home-tab" data-toggle="tab"><i class="fa fa-home"></i></a></li>
        <li><a href="#control-sidebar-settings-tab" data-toggle="tab"><i class="fa fa-gears"></i></a></li>
    </ul>
    <!-- Tab panes -->
    <div class="tab-content">
        <!-- Home tab content -->
        <div class="tab-pane" id="control-sidebar-home-tab">
            <h3 class="control-sidebar-heading">Recent Activity</h3>
            <ul class="control-sidebar-menu">
                <li>
                    <a href="javascript:void(0)">
                        <i class="menu-icon fa fa-birthday-cake bg-red"></i>
                        <div class="menu-info">
                            <h4 class="control-sidebar-subheading">Langdon's Birthday</h4>
                            <p>Will be 23 on April 24th</p>
                        </div>
                    </a>
                </li>
                <li>
                    <a href="javascript:void(0)">
                        <i class="menu-icon fa fa-user bg-yellow"></i>
                        <div class="menu-info">
                            <h4 class="control-sidebar-subheading">Frodo Updated His Profile</h4>
                            <p>New phone +1(800)555-1234</p>
                        </div>
                    </a>
                </li>
                <li>
                    <a href="javascript:void(0)">
                        <i class="menu-icon fa fa-envelope-o bg-light-blue"></i>
                        <div class="menu-info">
                            <h4 class="control-sidebar-subheading">Nora Joined Mailing List</h4>
                            <p>nora@example.com</p>
                        </div>
                    </a>
                </li>
                <li>
                    <a href="javascript:void(0)">
                        <i class="menu-icon fa fa-file-code-o bg-green"></i>
                        <div class="menu-info">
                            <h4 class="control-sidebar-subheading">Cron Job 254 Executed</h4>
                            <p>Execution time 5 seconds</p>
                        </div>
                    </a>
                </li>
            </ul>
            <!-- /.control-sidebar-menu -->
            <h3 class="control-sidebar-heading">Tasks Progress</h3>
            <ul class="control-sidebar-menu">
                <li>
                    <a href="javascript:void(0)">
                        <h4 class="control-sidebar-subheading">
                            Custom Template Design
                            <span class="label label-danger pull-right">70%</span>
                        </h4>
                        <div class="progress progress-xxs">
                            <div class="progress-bar progress-bar-danger" style="width: 70%"></div>
                        </div>
                    </a>
                </li>
                <li>
                    <a href="javascript:void(0)">
                        <h4 class="control-sidebar-subheading">
                            Update Resume
                            <span class="label label-success pull-right">95%</span>
                        </h4>
                        <div class="progress progress-xxs">
                            <div class="progress-bar progress-bar-success" style="width: 95%"></div>
                        </div>
                    </a>
                </li>
                <li>
                    <a href="javascript:void(0)">
                        <h4 class="control-sidebar-subheading">
                            Laravel Integration
                            <span class="label label-warning pull-right">50%</span>
                        </h4>
                        <div class="progress progress-xxs">
                            <div class="progress-bar progress-bar-warning" style="width: 50%"></div>
                        </div>
                    </a>
                </li>
                <li>
                    <a href="javascript:void(0)">
                        <h4 class="control-sidebar-subheading">
                            Back End Framework
                            <span class="label label-primary pull-right">68%</span>
                        </h4>
                        <div class="progress progress-xxs">
                            <div class="progress-bar progress-bar-primary" style="width: 68%"></div>
                        </div>
                    </a>
                </li>
            </ul>
            <!-- /.control-sidebar-menu -->
        </div>
        <!-- /.tab-pane -->
        <!-- Stats tab content -->
        <div class="tab-pane" id="control-sidebar-stats-tab">Stats Tab Content</div>
        <!-- /.tab-pane -->
        <!-- Settings tab content -->
        <div class="tab-pane" id="control-sidebar-settings-tab">
            <form method="post">
                <h3 class="control-sidebar-heading">General Settings</h3>
                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Report panel usage
                        <input type="checkbox" class="pull-right" checked>
                    </label>
                    <p>
                        Some information about this general settings option
                    </p>
                </div>
                <!-- /.form-group -->
                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Allow mail redirect
                        <input type="checkbox" class="pull-right" checked>
                    </label>
                    <p>
                        Other sets of options are available
                    </p>
                </div>
                <!-- /.form-group -->
                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Expose author name in posts
                        <input type="checkbox" class="pull-right" checked>
                    </label>
                    <p>
                        Allow the user to show his name in blog posts
                    </p>
                </div>
                <!-- /.form-group -->
                <h3 class="control-sidebar-heading">Chat Settings</h3>
                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Show me as online
                        <input type="checkbox" class="pull-right" checked>
                    </label>
                </div>
                <!-- /.form-group -->
                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Turn off notifications
                        <input type="checkbox" class="pull-right">
                    </label>
                </div>
                <!-- /.form-group -->
                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Delete chat history
                        <a href="javascript:void(0)" class="text-red pull-right"><i class="fa fa-trash-o"></i></a>
                    </label>
                </div>
                <!-- /.form-group -->
            </form>
        </div>
        <!-- /.tab-pane -->
    </div>
</aside>
<!-- /.control-sidebar -->
<!-- Add the sidebar's background. This div must be placed
     immediately after the control sidebar -->
<div class="control-sidebar-bg"></div>

okLims/Views/Shared/_AdminlteFooter.cshtml
<footer class="main-footer">
    <div class="pull-right hidden-xs">
        <b>Version</b> 1.0.0
    </div>
    <strong>BioreactorLims &copy; 2019 <a href="https://okLims.co">okLims</a>.</strong>
</footer>

okLims/Views/Shared/_AdminlteLayoutBoxed.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>@ViewData["Title"]</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=yes" name="viewport">
    <!-- Bootstrap 3.3. -->
    <link rel="stylesheet" href="~/adminlte/components/bootstrap/dist/css/bootstrap.min.css">
 
    <link rel="stylesheet" href="~/adminlte/components/font-awesome/css/font-awesome.min.css">

    <link rel="stylesheet" href="~/adminlte/components/Ionicons/css/ionicons.min.css">
    <link rel="stylesheet" href="~/adminlte/dist/css/AdminLTE.min.css">
    <!-- AdminLTE Skins. Choose a skin from the css/skins-->
       
    <link rel="stylesheet" href="~/adminlte/dist/css/skins/_all-skins.min.css">
    <link rel="stylesheet" href="~/css/site.min.css" />
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <!-- Google Font -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>
<!-- ADD THE CLASS layout-boxed TO GET A BOXED LAYOUT -->
<body class="hold-transition skin-blue layout-boxed sidebar-mini">
    <!-- Site wrapper -->
    <div class="wrapper">
        @Html.Partial("_AdminlteMainHeader")
        <!-- Left side column. contains the logo and sidebar -->
        @Html.Partial("_AdminlteMainSidebar")
        <!-- Content Wrapper. Contains page content -->
        @RenderBody()
        <!-- /.content-wrapper -->
        @Html.Partial("_AdminlteFooter")
        <!-- Control Sidebar -->
        @Html.Partial("_AdminlteControlSidebar")
    </div>

    <script src="~/adminlte/components/jquery/dist/jquery.min.js"></script>


    <script src="~/adminlte/components/bootstrap/dist/js/bootstrap.min.js"></script>

    <script src="~/adminlte/components/jquery-slimscroll/jquery.slimscroll.min.js"></script>

    <script src="~/adminlte/components/fastclick/lib/fastclick.js"></script>

    <script src="~/adminlte/dist/js/adminlte.min.js"></script>

    <script src="~/adminlte/dist/js/demo.js"></script>

</body>
</html>

okLims/Views/Shared/_AdminlteLayoutCollapsed.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>@ViewData["Title"]</title>
    <!-- Tell the browser to be responsive to screen width --->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=yes" name="viewport">

    <link rel="stylesheet" href="~/adminlte/components/bootstrap/dist/css/bootstrap.min.css">

    <link rel="stylesheet" href="~/adminlte/components/font-awesome/css/font-awesome.min.css">

    <link rel="stylesheet" href="~/adminlte/components/Ionicons/css/ionicons.min.css">

    <link rel="stylesheet" href="~/adminlte/dist/css/AdminLTE.min.css">

    <link rel="stylesheet" href="~/adminlte/dist/css/skins/_all-skins.min.css" />
    <link rel="stylesheet" href="~/css/site.min.css" />
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <!-- Google Font -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>
<!-- ADD THE CLASS layout-boxed TO GET A BOXED LAYOUT -->
<body class="hold-transition skin-blue sidebar-collapse sidebar-mini">
    <!-- Site wrapper -->
    <div class="wrapper">
        @Html.Partial("_AdminlteMainHeader")
        <!-- Left side column. contains the logo and sidebar -->
        @Html.Partial("_AdminlteMainSidebar")
        <!-- Content Wrapper. Contains page content -->
        @RenderBody()
        <!-- /.content-wrapper -->
        @Html.Partial("_AdminlteFooter")
        <!-- Control Sidebar -->
        @Html.Partial("_AdminlteControlSidebar")
    </div>
    <!-- ./wrapper -->
    <!-- jQuery 3 -->
    <script src="~/adminlte/components/jquery/dist/jquery.min.js"></script>

    <script src="~/adminlte/components/bootstrap/dist/js/bootstrap.min.js"></script>

    <script src="~/adminlte/components/jquery-slimscroll/jquery.slimscroll.min.js"></script>

    <script src="~/adminlte/components/fastclick/lib/fastclick.js"></script>

    <script src="~/adminlte/dist/js/adminlte.min.js"></script>
    <script src="~/adminlte/dist/js/demo.js"></script>

</body>
</html>

okLims/Views/Shared/_AdminlteLayoutFixed.cshtml
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>@ViewData["Title"]</title>
        <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
        <!-- Tell the browser to be responsive to screen width -->
        <!-- Bootstrap 3.3.7 -->
    <link rel="stylesheet" href="~/adminlte/components/bootstrap/dist/css/bootstrap.min.css">

    <link rel="stylesheet" href="~/adminlte/components/font-awesome/css/font-awesome.min.css">

    <link rel="stylesheet" href="~/adminlte/components/Ionicons/css/ionicons.min.css">

    <link rel="stylesheet" href="~/adminlte/dist/css/AdminLTE.min.css">

    <link rel="stylesheet" href="~/adminlte/dist/css/skins/_all-skins.min.css">   <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <link rel="stylesheet" href="~/css/site.min.css" />
        <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
        <!-- Google Font -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
    </head>
    <!-- ADD THE CLASS layout-boxed TO GET A BOXED LAYOUT -->
    <body class="hold-transition skin-blue fixed sidebar-mini">
        <!-- Site wrapper -->
        <div class="wrapper">
            @Html.Partial("_AdminlteMainHeader")
            <!-- Left side column. contains the logo and sidebar -->
            @Html.Partial("_AdminlteMainSidebar")
            <!-- Content Wrapper. Contains page content -->
            @RenderBody()
            <!-- /.content-wrapper -->
            @Html.Partial("_AdminlteFooter")
            <!-- Control Sidebar -->
            @Html.Partial("_AdminlteControlSidebar")
        </div>
        <!-- jQuery 3 -->
        <script src="~/adminlte/components/jquery/dist/jquery.min.js"></script>
 

        <script src="~/adminlte/components/bootstrap/dist/js/bootstrap.min.js"></script>

        <script src="~/adminlte/components/jquery-slimscroll/jquery.slimscroll.min.js"></script>

        <script src="~/adminlte/components/fastclick/lib/fastclick.js"></script>

        <script src="~/adminlte/dist/js/adminlte.min.js"></script>

        <script src="~/adminlte/dist/js/demo.js"></script>

    </body>
</html>

okLims/Views/Shared/_AdminlteMainHeader.cshtml
@model okLims.Models.ApplicationUser
@inject okLims.Data.ApplicationDbContext Context


@{
    ApplicationUser profile = Context.ApplicationUser.SingleOrDefault(x => x.ApplicationUserId.Equals(Model.Id));
}

<header class="main-header">
    <!-- Logo -->
    <a href="/" class="logo">
        <!-- mini logo for sidebar mini 50x50 pixels -->
        <span class="logo-mini"><b>Stuff and Things</b></span>
        <!-- logo for regular state and mobile devices -->
        <span class="logo-lg"><b>Bioreactor</b>LIMS</span>
    </a>
    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top">
        <!-- Sidebar toggle button-->
        <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
            <span class="sr-only">Toggle navigation</span>
        </a>
        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
                @if (Model != null)
                {
                    <!-- User Account: style can be found in dropdown.less -->
                    <li class="user-footer">
           
                            <button type="submit" href="@Url.Action("ApplicationUser", "UserRole")" class="btn btn-default btn-flat">Profile</button>                       
                   
                                <button type="submit" asp-controller="Account" asp-action="Logout" formmethod="post" class="btn btn-default btn-flat">Sign out</button>
                            
                   
                    </li>}
            </ul>

            </div>
            </nav>
</header>

okLims/Views/Shared/_LayoutCalender.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>FullCalendar in .NET Core</title>

    <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.9.0/fullcalendar.min.css' />
    <environment include="Development">
        <link rel="stylesheet" href="~/css/calendar.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="~/css/calendar.min.css" asp-append-version="true" />
    </environment>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
</head>
<body>
    @RenderBody()

    <script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js'></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <script src='https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.22.2/moment.min.js'></script>
    <script src='https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.9.0/fullcalendar.min.js'></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/qtip2/3.0.3/jquery.qtip.min.css" rel="stylesheet" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/qtip2/3.0.3/jquery.qtip.min.js"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/flatpickr/4.5.2/flatpickr.min.css" rel="stylesheet" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/flatpickr/4.5.2/flatpickr.min.js"></script>
    @*<script src="https://cdn.jsdelivr.net/npm/promise-polyfill@7/dist/polyfill.min.js"></script>*@
    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>

    <environment include="Development">
        <script src="~/js/calendar.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="~/js/calendar.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>